export enum DISPLAY_LEVEL {
  JUMP_NO_ATTR,
  JUMP,
  RESET,
  DELETE_AND_JUMP_STATEMENT,
  JUMP_AND_COLORS_STMTS,
  STATEMENT_GROUPS,
  SET_STROKE_WITH_PARAMS,
  TURN_NO_ATTR,
  TURN_TO_ANGLE,
  SET_STROKE_WIDTH,
  SET_PENCIL_POSITION,
  OTHER
}